### ISSUE TITLE
No config documentation.

### ISSUE THREAD

**Issue by bearbin** [Smattr/needtoknow#2]
There is no documentation of the config format, could you upload a example file?

**Comment by Smattr** [comment]
There lack of documentation is because there was only one user I knew of (myself), so thank you for your interest :) It could certainly use with an example. I'll add something in the next few days.

**Comment by Smattr** [comment]
I've just pushed some explanatory text, though it's still pretty brief. Please let me know if anything is unclear or if there are specific questions you have. Thanks :)

**Comment by bearbin** [comment]
That was just what I needed, thanks for writing it up :)
