### ISSUE TITLE
Unusual license choice 

### ISSUE THREAD

**Issue by bearbin** [Smattr/needtoknow#6]
CC BY-NC is an unusual license for software, I don't know what your reasons for choosing it are but you might want to look into changing it. Creative Commons advises that their licenses should not be used for software: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

**Comment by Smattr** [comment]
Yes, good point, that is unusual. I don't recall why I picked CC BY-NC, so I've changed it to public domain instead.
